{
 "title": "Backend",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Socket.IO Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "socket_io_connected" }
   ]
  },
  {
   "title": "Request rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Socket.IO events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "socket_io_events_sent_total", "legendFormat": "{{ event }}" }
   ]
  },
  {
   "title": "Node event loop latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds" }
   ]
  },
  {
   "title": "Node active handles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles", "legendFormat": "{{ type }}" }
   ]
  }
 ]
}